listener:
  channel_name: TradingView Alerts
  log_file: alerts.log
  log_level: INFO
telegram:
  api_hash: 35ba575278923166895f4e4bcc1d1cee
  api_id: '38568434'
  phone: '+14382208442'
  session_name: listener_session
